import type { Metadata } from "next";
import "./globals.css";
import { AppSidebar } from "@/components/sidebar"
import { SidebarProvider, SidebarTrigger, SidebarInset } from "@/components/ui/sidebar"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <SidebarProvider>
          <div className="flex h-screen">
            <AppSidebar />
            <SidebarInset className="flex-1 overflow-auto">
              <header className="flex h-16 items-center border-b px-4">
                <SidebarTrigger />
                <h1 className="ml-4 text-xl font-semibold">Smart Delivery App</h1>
              </header>
              <main className="p-6">
                {children}
              </main>
            </SidebarInset>
          </div>
        </SidebarProvider>
      </body>
    </html>
  )
}


