import type { Metadata } from "next";
import "./globals.css";
import { AppSidebar } from "@/components/sidebar"
import { SidebarProvider, SidebarTrigger, SidebarInset } from "@/components/ui/sidebar"
import { Toaster } from "@/components/ui/toaster"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className="h-full">
      <body className="min-h-full">
        <SidebarProvider>
          <div className="flex min-h-screen w-full">
            <AppSidebar />
            <SidebarInset className="flex flex-col flex-1 min-h-screen w-full">
              <header className="flex h-16 items-center border-b px-4 shrink-0">
                <SidebarTrigger />
                <h1 className="ml-4 text-xl font-semibold">Smart Delivery App</h1>
              </header>
              <main className="flex-1 p-6 overflow-auto">
                {children}
              </main>
              <Toaster />
            </SidebarInset>
          </div>
        </SidebarProvider>
      </body>
    </html>
  )
}